motor_polynomial_parameters_displacement2force:
  - [0, 11.54916, 0.4726624]
  - [1, 3.004206, 0.8573538]
  - [2, 2.098613, 0.9267733]
  - [3, 0, 0, 0]
  - [4, 0, 0, 0]
  - [5, 0, 0, 0]
  - [6, 0, 0, 0]
  - [7, -3.928751, 0.9207964]
  - [8, 6.789773, 0.7775457]
  - [9, -5.182672, 0.9519135]
  - [10, -1.751716, 0.935832]
  - [11, 6.315656, 0.7849689]
  - [12, -0.3161697, 0.8381798]
  - [13, 0, 0, 0]
motor_polynomial_parameters_force2displacement:
  - [0, -23.35386, 2.084921]
  - [1, -1.680643, 1.124931]
  - [2, -0.7977692, 1.048678]
  - [3, 0, 0, 0]
  - [4, 0, 0, 0]
  - [5, 0, 0, 0]
  - [6, 0, 0, 0]
  - [7, 6.212178, 1.039864]
  - [8, -2.324675, 1.142573]
  - [9, 5.605415, 1.046595]
  - [10, 2.62372, 1.051277]
  - [11, -0.7776121, 1.111585]
  - [12, 4.941622, 1.083228]
  - [13, 0, 0, 0]